### ISSUE TITLE
Considering adding a license

### ISSUE THREAD

**Issue by kraktus** [paralogical/rarest-move-in-chess#2]
Hey! Very nice video of yours, it’s always great to see Lichess database put in use for insights.

There’s currently no license in this repository, meaning your code is copyrighted. 

If that’s an oversight you might consider adding one for it to be open-source, https://choosealicense.com/ is a good site that explain the different possibilities.

Cheers,

**Comment by jogerj** [comment]
+1
Usually for datasets, some variant of Creative Commons license would be used, but sections of code in the repo could also be licensed differently. [See following guidelines of CC](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

**Comment by paralogical** [comment]
Thank you for this, this was an oversight. I added an MIT license.
